### ISSUE TITLE
Selfhosted docker-compose method failed.

### ISSUE THREAD

**Issue by ericvlog** [mhdzumair/MediaFusion#143]
failed to create network docker-compose_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

hello, I try selfhost with docker compose

as my system already have prowlarr and nginx proxy manager

so below is my docker-compose and .env 

HOST_URL="https://mediafusion.mydomain.duckdns.org"
MONGO_URI="mongodb://mongodb:27017/mediafusion"
REDIS_URL="redis://redis:6379"
PROWLARR_URL="http://192.168.1.100:9696"
PROWLARR_API_KEY=66fab75acab44fb0a29fecc88c42c89f2
PROWLARR_IMMEDIATE_MAX_PROCESS=5
PROWLARR_IMMEDIATE_MAX_PROCESS_TIME=15
PROWLARR_SEARCH_INTERVAL_HOUR="24"
IS_SCRAP_FROM_TORRENTIO="true"
ENABLE_RATE_LIMIT="false"
ENABLE_TAMILMV_SEARCH_SCRAPER="false"

```
version: '3.8'
services:
  mediafusion:
    image: mhdzumair/mediafusion:v3.7.4
    ports:
      - "8899:80"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
  mongodb:
    image: mongo:4.4.6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  dramatiq-worker:
    image: mhdzumair/mediafusion:v3.7.4
    command: ["pipenv", "run", "dramatiq-gevent", "api.task"]
    env_file:
      - .env
    depends_on:
      - mongodb

  scraper:
    image: mhdzumair/mediafusion:v3.7.4
    command: ["pipenv", "run", "python", "-m", "api.scheduler"]
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongo-data:
```

**Comment by mhdzumair** [comment]
Its issue with your docker usable network ips, Try with following solutions

1. Remove Unused Networks
```bash
# To list all networks:
docker network ls

# To remove a network:
docker network rm [NETWORK_ID]
```

2. Try to Restart Docker
3. Cleanup Docker System
```bash
docker system prune
```

4. Manually Specify a Subnet
```yaml
version: '3.8'
services:
  mediafusion:
    image: mhdzumair/mediafusion:v3.7.4
    ports:
      - "8899:80"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - mediafusion_network

  mongodb:
    image: mongo:4.4.6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mediafusion_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mediafusion_network

  dramatiq-worker:
    image: mhdzumair/mediafusion:v3.7.4
    command: ["pipenv", "run", "dramatiq-gevent", "api.task"]
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - mediafusion_network

  scraper:
    image: mhdzumair/mediafusion:v3.7.4
    command: ["pipenv", "run", "python", "-m", "api.scheduler"]
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - mediafusion_network

volumes:
  mongo-data:

networks:
  mediafusion_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"

```
