### ISSUE TITLE
Mediafusion is not indexing TamilMV sites in selfhosted instance.

### ISSUE THREAD

**Issue by rrevanth** [mhdzumair/MediaFusion#364]
I'm trying to use mediafusion self hosted instance and for some reason, it's failing to index 1tamilmv sites resulting in few or no results for indian movies.

Here is my docker compose file

```
services:
  mediafusion:
    container_name: mediafusion
    hostname: mediafusion
    image: mhdzumair/mediafusion:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: mf-mongo
    hostname: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: mf-redis
    restart: unless-stopped
    hostname: redis
    ports:
      - "6379:6379"

  dramatiq-worker:
    container_name: mf-dramatiq
    image: mhdzumair/mediafusion:latest
    restart: unless-stopped
    command: ["pipenv", "run", "dramatiq", "api.task", "-p", "1", "-t", "1", "--queues", "scrapy"]
    env_file:
      - .env
    depends_on:
      - mongodb

  browserless:
    container_name: mf-browserless
    restart: unless-stopped
    image: ghcr.io/browserless/chromium
    ports:
      - "3000:3000"
volumes:
  mongo-data:
```

<img width="1133" alt="Screenshot 2024-11-19 at 12 35 33 PM" src="https://github.com/user-attachments/assets/26382f9f-8a4e-4114-9380-ecd321f13de5">
